src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Article::class)]
    private Collection $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): string
    {
        return "$this->firstName $this->lastName";
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setUser($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getUser() === $this) {
                $article->setUser(null);
            }
        }

        return $this;
    }
}

templates/Components/_articleList.html.twig
{% for article in articles %}
	{% include 'Components/_card.html.twig' %}
{% else %}
	<div class="alert alert-info w-100" role="alert">
		<i class="bi bi-info-square-fill"></i>
		<span>Il n'y a pas d'article correspondant à votre recherche</span>
	</div>
{% endfor %}

templates/Components/_card.html.twig
<div class="blog-card" id="article-{{ article.id }}">
	<a href="{{ path('app.article.show', {slug: article.slug}) }}" class="link-img">
		{% for image in article.images| slice(0,1) %}
			<img src="{{ vich_uploader_asset(image) }}" alt="{{ article.titre }}" class="blog-card-img" loading="lazy">
		{% else %}
			<img src="https://picsum.photos/350/250" alt="{{ article.titre }}" class="blog-card-img" loading="lazy">
		{% endfor %}
	</a>
	<div class="blog-card-content">
		<p class="blog-card-date text-muted">{{ article.createdAt|format_datetime('full', 'none') }}</p>
		<a href="{{ path('app.article.show', {slug: article.slug}) }}">
			<h2 class="blog-card-header">{{ article.titre }}</h2>
		</a>
		<p class="blog-card-contenu">{{ article.contenu|striptags|slice(0, 100) ~ '...' }}</p>
		<p class="blog-card-author">{{ article.user.fullName }}</p>
		<p class="text-muted">
			{% for categorie in article.categories %}
				#{{ categorie.titre }}
			{% endfor %}
		</p>
		{% if app.request.get('_route') == 'admin.article.index' %}

			<div class="form-check form-switch">
				<input class="form-check-input" type="checkbox" id="article-actif-{{ article.id }}" data-actif-id="{{ article.id }}" {{ article.actif ? 'checked' }}>
				<label class="form-check-label" for="article-actif-{{ article.id }}">Actif</label>
			</div>

			<div class="d-flex justify-content-between mt-auto">
				<a href="{{ path('admin.article.update', {id: article.id}) }}" class="btn btn-warning">Modifier</a>
				<form action="{{ path('admin.article.delete', {id: article.id}) }}" method="POST" onsubmit="return confirm('Êtes-vous sur de vouloir supprimer cet article ?')">
					<input type="hidden" name="id" value="{{ article.id }}">
					<input type="hidden" name="token" value="{{ csrf_token('delete' ~ article.id) }}">
					<button type="submit" class="btn btn-danger">Supprimer</button>
				</form>
			</div>
		{% endif %}
	</div>
</div>

templates/Components/_count.html.twig
<div class="js-filter-count">
	{{ articles.getTotalItemCount }}
	{{ articles.getTotalItemCount > 1 ? 'Articles' : 'Article' }}
</div>

templates/Components/_form.html.twig
{{ form_start(form, {'attr': {'class': 'card p-3 form-filter js-filter-form'}}) }}

<div class="loader">
	<div class="js-loading spinner-grow text-primary float-right" role="status" aria-hidden="true" style="display: none">
		<span class="visually-hidden">Loading...</span>
	</div>
</div>

{{ form_widget(form.title) }}

<h3 class="my-3">{{ form.tags.vars.label }}</h3>
{{ form_widget(form.tags, {'attr': {'class': 'd-flex gap-2 flex-wrap'}}) }}

<h3 class="mb-3">{{ form.authors.vars.label }}</h3>
{{ form_widget(form.authors, {'attr': {'class': 'd-flex gap-2 flex-wrap'}}) }}

<button type="submit" class="btn btn-primary mt-2">Filtrer</button>
{{ form_end(form) }}

templates/Components/_pagination.html.twig
<div class="mt-4 js-filter-pagination">
	{{ knp_pagination_render(articles) }}
</div>

templates/Components/_sortable.html.twig
<div class="js-filter-sortable d-flex gap-2">
	{{ knp_pagination_sortable(articles, 'Date ', 'a.createdAt', {'direction': 'DESC', 'class': 'btn btn-primary d-flex gap-1'}) }}
	{{ knp_pagination_sortable(articles, 'Titre ', 'a.titre', {'direction': 'ASC', 'class': 'btn btn-primary d-flex gap-1'}) }}
</div>